server:
  address: 0.0.0.0
  port: ${PORT:8080}
api:
  version: /api/v1
spring:
  application:
    name: onlineStore
  datasource:
    url: ${MYSQL_URL}
    username: ${MYSQLUSER}
    password: ${MYSQLPASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB
  ai:
    openai:
      api-key: ${OPEN_API_KEY}
    vectorstore:
      chroma:
        base-url: https://chromavectordb.fly.dev
        initialize-schema: false
        collection-name: image_collection
        database-name: default_database
        tenant-name: default_tenant
auth:
  token:
    accessExpirationInMills: 300000
    refreshExpirationInMills: 2592000000
    jwtSecret: ${JWT_SECRET}
app:
  useSecureCookie: false
stripe:
  secret:
    key: ${STRIPE_SECRET_KEY}
management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: never
logging:
  level:
    root: ERROR
    com.zaxxer.hikari: ERROR
    org.springframework.jdbc: ERROR